services:
  - type: web
    name: engram-api
    runtime: python
    branch: deployment
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: "gemini-3-flash-preview"
      - key: GEMINI_EMBEDDING_MODEL
        value: "gemini-embedding-001"
      - key: PG_HOST
        value: "db.jatdhhgawrfdslvkjpcx.supabase.co"
      - key: PG_PORT
        value: "5432"
      - key: PG_USER
        value: "postgres"
      - key: PG_PASSWORD
        sync: false
      - key: PG_DB
        value: "postgres"
      - key: QDRANT_URL
        value: "https://51ca38e8-3f72-496c-b0d9-f93f57f172af.eu-west-2-0.aws.cloud.qdrant.io"
      - key: QDRANT_API_KEY
        sync: false
      - key: SCENE_SIMILARITY_THRESHOLD
        value: "0.75"
    healthCheckPath: /stats
